### ISSUE TITLE
Cannot find NVM itself

### ISSUE THREAD

**Issue by bahmutov** [btleffler/node-nvm-api#1]
Hi, trying to use the api and seems it cannot find nvm - maybe because of bash shell?

```
Error Calling NVM. Make sure it's properly installed and sourced.
Error: Command failed: /bin/sh -c nvm root
/bin/sh: nvm: command not found
```

**Comment by bahmutov** [comment]
The nvm is there in ~/.nvm and the nvm itself is working very well

```
$ nvm --version
0.29.0
```

**Comment by bahmutov** [comment]
Found a better way to run nvm - we need to source its script first, for example one could run the following `[ 'sh', '-c', '. ~/.nvm/nvm.sh && nvm ls' ]`

**Comment by bahmutov** [comment]
Thank you, now my tool https://github.com/bahmutov/all-nvm will use your module again - maybe setup semantic-release so you don't have to manually publish things? https://github.com/semantic-release/semantic-release

**Comment by btleffler** [comment]
Thanks for the tip! :thumbsup:

Looks like I'll need to write some tests when I get a chance too.
